</div><!--/span9-->
</div><!--/row-->
<hr>
<footer class="text-center">
        <p>Creado con cariño por
                <a href="https://www.twitter.com/nelsonrojas" class="text bold color theme"><span class="icon icon-heart"></span> Nelson Rojas</a>
              </p>
          <small>Ingeniero talquino, Chile.</small>
          <small><?php echo 'Ejecutado en ', round((microtime(1) - $_SERVER['REQUEST_TIME_FLOAT'])*1000, 4), ' ms. usando ', number_format(memory_get_usage() / 1048576, 3), ' MB de memoria'?></small>
</footer>

</div><!--/.fluid-container-->
<script type="text/javascript" src="<?=PUBLIC_PATH;?>js/jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="<?=PUBLIC_PATH;?>js/bootstrap.min.js"></script>

</body>
</html>
