<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <title>Isalia Micro Framework</title>
	<link href="<?=PUBLIC_PATH;?>css/bootstrap.min.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }

      @media (max-width: 980px) {
        /* Enable use of floated navbar text */
        .navbar-text.pull-right {
          float: none;
          padding-left: 5px;
          padding-right: 5px;
        }
      }
    </style>
  </head>
  <body>
	<div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">Isalia</a>
          <div class="nav-collapse collapse">
            <p class="navbar-text pull-right">
			  <?php if ( !Auth::isLogged() ) { ?>
                	<a href="<?= PUBLIC_PATH;?>index/login" class="navbar-link">Login</a>
				<?php } else { ?>
					Hi <?=Auth::get();?> <a href="<?= PUBLIC_PATH;?>index/logout" class="navbar-link">Logout</a>
				<?php } ?>

            </p>
            <ul class="nav">
              <li class="active"><a href="<?= PUBLIC_PATH;?>">Home</a></li>
              <li><a href="<?= PUBLIC_PATH;?>categorias">Categorías</a></li>
              <li><a href="<?= PUBLIC_PATH;?>index/contacto">Contacto</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Categorías</li>
              <?php foreach((new Category)->all() as $categoria): ?>
                <li><a href="#"><?= $categoria['name'] ?></a></li>
              <?php endforeach; ?>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span10">
          <?php if ((new Flash)->hasMessages()) { ?>
            <?= (new Flash)->render(); ?>
          <?php } ?>
