<h3>Agregar categorías</h3>
  <div class="row-fluid">

            <form id="form" name="form" method="post">
              <label>Nombre</label>
              <input type="text" name="category[name]" id="category.name" />

              <label>Posicion</label>
              <input type="number" name="category[pos]" id="category.pos" />
              <br/>
              <input type="submit" name="enviar" value="Agregar" class="btn btn-primary">
              <?= Html::link('Cancelar', 'categorias/index', 'class="btn btn-default"'); ?> 
            </form>

  </div>
