
  <?= Html::link('Agregar', 'categorias/add/', 'class="btn btn-success pull-right"'); ?>
  <h3>Lista de categorías</h3>
    <div class="row-fluid">

          <table class="table table-bordered table-condensed table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Opciones</th>
                </tr>
            </thead>
            <tbody>
              <?php foreach($categorias as $cat): ?>
                <tr>
                    <td><?= $cat['id'];?></td>
                    <td><?= $cat['name'];?></td>
                    <td>
                      <?= Html::link('Editar', 'categorias/edit/' . $cat['id'], 'class="btn btn-info"'); ?>
                      <?= Html::link('Eliminar', 'categorias/del/' . $cat['id'], 'class="btn btn-danger"'); ?>
                    </td>
                </tr>
              <?php endforeach; ?>
            </tbody>
          </table>

    </div>
